name: Build (and upload)

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

env:
  UPLOAD_BRANCHES: master develop
  ARTIFACTS_PATH: artifacts
  DEPENDENCIES: uuid-dev libsqlite3-dev liblua5.3-dev libssl-dev

jobs:
  build:
    concurrency: ci-build-${{ github.ref_name }}-${{ matrix.variant }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      fail-fast: false
      matrix:
        variant:
          - linux/amd64
          - linux/i386
        allow-failure: [false]
        include:
          - variant: linux/arm64
            allow-failure: true
          - variant: linux/armhf
            allow-failure: true
          #- variant: linux/armel
          #  allow-failure: true
    steps:
    - uses: actions/checkout@v4

    - run: cp .github/build.sh /tmp

    - run: bash /tmp/build.sh "${{ matrix.variant }}"

    - uses: actions/upload-artifact@v3
      if: ${{ env.PLATFORM != '' && env.ARCHITECTURE != '' }}
      with:
        name: build-${{ github.ref_name }}-${{ env.PLATFORM }}-${{ env.ARCHITECTURE }}
        path: '*.tar.gz*'
        retention-days: 1

  upload:
    concurrency: ci-build-upload
    needs: build
    permissions:
      pages: write
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
          sparse-checkout-cone-mode: false

      - run: cp .github/upload.sh /tmp

      - run: git sparse-checkout disable

      - uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages

      - uses: actions/download-artifact@v3
        with:
          path: ${{ env.ARTIFACTS_PATH }}

      - run: bash /tmp/upload.sh "${{ env.ARTIFACTS_PATH }}"

      - run: git branch -m gh-pages gh-pages.old
        continue-on-error: true

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          commit-message: Uploading binaries
          single-commit: true
          force: true
